# Generated by Django 5.0 on 2023-12-11 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_rt_unique_together_alter_rw_unique_together'),
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='RW',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.rw'),
            preserve_default=False,
        ),
    ]
