# Generated by Django 4.2.7 on 2023-11-29 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('kecamatan', models.CharField(max_length=255)),
                ('kabupaten', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('RW', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.rw')),
            ],
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=255)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.anggota')),
            ],
        ),
        migrations.AddField(
            model_name='anggota',
            name='RT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.rt'),
        ),
        migrations.AddField(
            model_name='anggota',
            name='RW',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.rw'),
        ),
        migrations.AddField(
            model_name='anggota',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.pengguna'),
        ),
    ]
