# Generated by Django 4.2.7 on 2023-11-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='RW',
        ),
        migrations.AlterField(
            model_name='anggota',
            name='pengguna',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.pengguna'),
        ),
        migrations.AlterField(
            model_name='pengurus',
            name='anggota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.anggota'),
        ),
    ]
