# Generated by Django 4.2.7 on 2023-12-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_anggota_rw_alter_anggota_pengguna_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rt',
            unique_together={('RW', 'nomor')},
        ),
        migrations.AlterUniqueTogether(
            name='rw',
            unique_together={('nomor', 'kecamatan', 'kabupaten', 'provinsi')},
        ),
    ]
