# Generated by Django 4.2.8 on 2023-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKegiatan', models.CharField(max_length=200)),
                ('deskripsiKegiatan', models.TextField()),
                ('waktuKegiatan', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
