# Generated by Django 4.2.8 on 2023-12-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_rt_unique_together_alter_rw_unique_together'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='namaPengurus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.pengurus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='waktuKegiatan',
            field=models.DateTimeField(verbose_name='Waktu Kegiatan'),
        ),
    ]
