# Generated by Django 4.2.8 on 2023-12-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_rt_unique_together_alter_rw_unique_together'),
        ('agenda', '0004_alter_kegiatan_pengurus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='pengurus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pengurus'),
        ),
    ]
