# Generated by Django 4.2.7 on 2023-12-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('Kegiatan', 'Kegiatan'), ('Silahturahmi', 'Silahturahmi'), ('Kebaikan', 'Kebaikan'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.pengguna')),
            ],
        ),
    ]
