# Generated by Django 4.2.7 on 2023-12-02 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
