# Generated by Django 4.2.7 on 2023-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0002_alter_pengumuman_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
