# Generated by Django 4.2.7 on 2023-12-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_rt_unique_together_alter_rw_unique_together'),
        ('pengumuman', '0003_alter_pengumuman_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengumuman',
            name='user',
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='anggota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.anggota'),
            preserve_default=False,
        ),
    ]
