# Generated by Django 4.2.7 on 2023-12-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0004_remove_pengumuman_user_pengumuman_anggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/attachments/'),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
