# Generated by Django 4.2.7 on 2023-12-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0007_category_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='category',
            new_name='album',
        ),
    ]
