# Generated by Django 4.2.7 on 2023-12-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0008_rename_category_album_rename_category_gallery_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='RW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('kecamatan', models.CharField(max_length=40)),
                ('kabupaten', models.CharField(max_length=40)),
                ('provinsi', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('rw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygallery.rw')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mygallery.rt'),
            preserve_default=False,
        ),
    ]
