# Generated by Django 4.2.7 on 2023-12-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0012_alter_user_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rt',
            name='rw',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mygallery.rw'),
        ),
    ]
