# Generated by Django 4.2.7 on 2023-12-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0013_alter_rt_rw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mygallery.rt'),
        ),
    ]
