# Generated by Django 4.2.7 on 2023-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0015_remove_album_user_remove_gallery_user_album_rt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='rt',
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.CharField(default='admin', max_length=40),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
